app_homepage:
    path: /
    defaults: { _controller: AppBundle:App:index }

app_produits:
    path: /admin/produits/
    defaults: { _controller: AppBundle:Admin:produit }

app_produit:
    resource: "@AppBundle/Resources/config/routing/produit.yml"
    prefix:   /admin

app_contact:
    path: /contact
    defaults: { _controller: AppBundle:App:contact }
    methods: GET

app_contact_form:
    path: /contact
    defaults: { _controller: AppBundle:App:contactform }
    methods : POST

app_single:
    path: /single/{id}
    defaults: 
        _controller: AppBundle:App:single
    requirements:
        id: \d+
        _method: GET 
        
app_vente:
    path: /conditions-de-ventes/
    defaults: { _controller: AppBundle:App:vente }

app_panier:
    path: /user/panier
    defaults: { _controller: AppBundle:App:panier}

app_all:
    path: /all
    defaults: { _controller: AppBundle:App:all}

app_confident:
    path: /politique-confidentialit√©/
    defaults: { _controller: AppBundle:App:confident }